PyroConfigVersion:
  - 0.6.0
#   Edit each value to change if players can craft these items (true/false)
Recipes:
  - New Color Arrow: true
  - Color Arrow: true
  - New Chromatic Armor: true
  - Chromatic Armor: true
  - Bang Snowball: true
  - Rainbow Snowball: true
  - Remote Detonator: true
  - Firework TNT: true
  - Firework Sign: true
