PyroConfigVersion:
  - 0.6.0

recipes:
  color-arrows: true
  chromatic-armor: true
  bang-snowballs: true
  rainbow-snowballs: true
  remote-detonators: true
  firework-tnt: true
  firework-signs: true