name: Pyro
main: zedly.pyro.Pyro
version: 0.6.1
api-version: 1.14
commands:
  cannon:
    description: Fires an exploding item
    usage: /cannon <Item ID/Item Name>:<MaterialData?>
  color:
    description: Spawns color arrows
    usage: /color <color>/<r,g,b>
  py:
    description: Use Pyro commands
    usage: /py
  remote:
    description: Fires an exploding item
    usage: /remote <add/del> <channel name>
permissions:
  pyro.*:
    description: Enables permissions for the entire Pyro plugin
    children:
      pyro.cannon: true
      pyro.colorarrow: true
      pyro.egg: true
      pyro.firework: true
      pyro.party: true
      pyro.partyglobal: true
      pyro.remote: true
  pyro.cannon:
    description: Fires an exploding item.
    default: false
  pyro.colorarrow:
    description: Allows editing or creating color arrows.
    default: false
  pyro.egg:
    description: Drops the held item, disguised as a random mob egg.
    default: false
  pyro.firework:
    description: Allows creating Firework signs.
    default: false
  pyro.party:
    description: Allows usage of </py party> to start or stop a party around the user.
    default: false
  pyro.partyglobal:
    description: Allows usage of </py party global> to start or stop a global party.
    default: false
  pyro.remote:
    description: Allows creating remote controlled TNT and TNT detonators.
    default: false