name: Pyro
main: zedly.pyro.Pyro
version: 0.6.1
api-version: 1.14
commands:
  colorarrow:
    permission: pyro.colorarrow
    description: Spawns color arrows
    usage: /color <color>/<r,g,b>
  eegg:
    permission: pyro.eegg
    description: Drops the item you are holding disguised as a monster egg or a chest
    usage: /eegg
  eeggs:
    permission: pyro.eeggs  
    description: List how many easter eggs / christmas presents are left
    usage: /eeggs
  firework:
    permission: pyro.firework
    description: A graphical interface for crfeating firework items
    usage: /firework
  party:
    permission: pyro.party
    description: Continuously launches some fireworks around you or the entire server
    usage: /party (all)
  rainboom:
    permission: pyro.rainboom
    description: Produces a colorful firework trail when you fly
    usage: /rainboom
  retrieveeggs:
    permission: pyro.retrieveeggs
    description: Brings back all undiscovered easter eggs
    usage: /retrieveeggs
  rtnt:
    permission: pyro.rtnt
    description: Fires an exploding item
    usage: /remote <add/del> <channel name>
permissions:
  pyro.*:
    description: Enables permissions for the entire Pyro plugin
    children:
      pyro.cannon: true
      pyro.colorarrow: true
      pyro.eegg: true
      pyro.eeggs: true
      pyro.firework: true
      pyro.party: true
      pyro.partyglobal: true
      pyro.rainboom: true
      pyro.retrieveeggs: true
      pyro.rtnt: true
      pyro.item.*: true
      
  pyro.item.*:
    children:
      pyro.item.repulsor: true
      pyro.item.missile: true
      pyro.item.destructor: true
      pyro.item.spark: true
      pyro.item.signal: true
      pyro.item.bangball: true
      pyro.item.rainbowsnowball: true
      pyro.item.remotetrigger: true
      pyro.item.fireworktnt: true
     
  pyro.item.repulsor:
    default: false
  pyro.item.missile:
    default: false
  pyro.item.destructor:
    default: false
  pyro.item.spark:
    default: false
  pyro.item.signal:
    default: false
  pyro.item.bangball:
    default: false
  pyro.item.rainbowsnowball:
    default: false
  pyro.item.remotetrigger:
    default: false
  pyro.item.fireworktnt:
    default: false

  pyro.cannon:
    description: Fires an exploding item.
    default: false
  pyro.colorarrow:
    description: Allows editing or creating color arrows.
    default: false
  pyro.eegg:
    description: Drops the held item, disguised as a random mob egg.
    default: false
  pyro.eeggs:
    default: false
  pyro.firework:
    description: Allows creating Firework signs.
    default: false
  pyro.party:
    description: Allows usage of </py party> to start or stop a party around the user.
    default: false
  pyro.partyglobal:
    description: Allows usage of </py party global> to start or stop a global party.
    default: false
  pyro.rainboom:
    default: false
  pyro.retrieveeggs:
    default: false
  pyro.rtnt:
    description: Allows creating remote controlled TNT and TNT detonators.
    default: false